version: 0.1
default:
  build:
    parameters:
      cached: 'true'
      parallel: 'true'
  deploy:
    parameters:
      stack_name: {{ cookiecutter.service_name }}
      s3_bucket: {{ cookiecutter.sandbox_artifacts_bucket }}
      capabilities: CAPABILITY_IAM
      image_repositories: []