name: QA

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/shared-lint.yaml
    secrets: inherit

  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/shared-unit-tests.yaml
    secrets: inherit

  build-and-deploy:
    name: Build and Deploy SAM Application
    needs: [lint, unit-tests]
    strategy:
      matrix:
        region: [us-east-1]
    uses: ./.github/workflows/shared-sam-build-and-deploy.yaml
    with:
      AWS_REGION:  ${{ matrix.region }}
      CONFIG_ENV: qa
      WORKFLOW_ENV : QA
    secrets: inherit

  test-api:
    name: Test API
    needs: [build-and-deploy]
    uses: ./.github/workflows/shared-test-api.yaml
    with:
      WORKFLOW_ENV : QA
    secrets: inherit
