name: SAM Build & Deploy

on:
  workflow_call:
    inputs:
      CONFIG_ENV:
        description: Environment to use from samconfig.toml
        required: true
        type: string
      WORKFLOW_ENV:
        description: GitHub workflow environment to be able to access environment level secrets
        required: true
        type: string
      AWS_REGION:
        description: AWS Region the stack is being deployed to
        required: true
        type: string

jobs:
  build-and-deploy:
    name: Build and Deploy SAM Application
    runs-on: ubuntu-latest
    environment: ${{ inputs.WORKFLOW_ENV }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - uses: aws-actions/setup-sam@v2
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ENV_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ENV_SECRET_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}
      - name: SAM Build & Deploy
        run: |
          sam build
          sam deploy --config-env "${{ inputs.CONFIG_ENV }}" --resolve-s3 --no-fail-on-empty-changeset
