name: Portman Tests

on:
  workflow_call:
    inputs:
      WORKFLOW_ENV:
        description: GitHub workflow environment to be able to access environment level secrets
        required: true
        type: string

jobs:
  portman:
    name: Run Portman
    runs-on: ubuntu-latest
    environment: ${{ inputs.WORKFLOW_ENV }}
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ENV_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ENV_SECRET_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: Test API
        run: |
          npm install -g @apideck/portman
          npm ci
          aws cloudformation describe-stacks --stack-name task-service-api --query "Stacks[0].Outputs[?OutputKey=='ApiURL'].OutputValue" --output text
          npm run set-portman-config ./portman/portman-config.json ./portman/portman-cli.json ${{ inputs.WORKFLOW_ENV }}
          npm run portman