name: {{ cookiecutter.prod_stage_name }}

on:
  push:
    branches:
      - {{ cookiecutter.main_git_branch }}
  workflow_dispatch:

concurrency:
  group: {{ '${{ github.workflow }}' }}

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/shared-lint.yaml
    secrets: inherit

  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/shared-unit-tests.yaml
    secrets: inherit

  deploy-resources:
    name: Deploy SAM Resources
    needs: [lint, unit-tests]
    uses: ./.github/workflows/shared-deploy.yaml
    with:
      ENVIRONMENT: prod
      AWS_REGION: {{ cookiecutter.prod_region }}
      PIPELINE_EXECUTION_ROLE: {{ cookiecutter.prod_pipeline_execution_role }}
      CLOUDFORMATION_EXECUTION_ROLE: {{ cookiecutter.prod_cloudformation_execution_role }}
      ARTIFACTS_BUCKET_NAME: {{ cookiecutter.prod_artifacts_bucket }}
      STACK_NAME: {{ cookiecutter.stack_name }}
    secrets: inherit

  test-api:
    name: Test API
    needs: [deploy-resources]
    uses: ./.github/workflows/shared-test-api.yaml
    with:
      ENVIRONMENT : prod
      AWS_REGION: {{ cookiecutter.prod_region }}
      PIPELINE_EXECUTION_ROLE: {{ cookiecutter.prod_pipeline_execution_role }}
      STACK_NAME: {{ cookiecutter.stack_name }}
    secrets: inherit
