AWSTemplateFormatVersion: 2010-09-09
Description: Task Service - DynamoDB
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  TableName:
    Type: String
    Default: {{ cookiecutter.dynamodb_table_name }}

Resources:
  TaskServiceTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S